### ISSUE TITLE
Adaptive Intelligent Binning on 13C NMR spectra

### ISSUE THREAD

**Issue by mjmg** [INRA/NMRProcFlow#4]
Hi @djacob65 we were trying adaptive intelligent binning on 13C NMR spectra and no buckets are generated. 

Please advise if this is an NMRPROCFLOW limitation by design or of the original algorithm by De Meyer.

Thank You

**Comment by djacob65** [comment]
@mjmg  Sorry for the delay in response. I just tested with 13C the AI-Binning and it seems to work fine with my set of spectra. I guess you forgot to specify the noisy PPM range correctly, if it is the case it is normal that it did not work.
Regards

**Comment by mjmg** [comment]
@djacob65 I was only able to get binning from the less than 14 ppm range. 
![image](https://user-images.githubusercontent.com/14349710/144203422-9345380f-d921-4688-9316-889a01864219.png)



Would you care to look at our sample data and check how to get AI binning here? 
<edit - remove links>

Thank You

**Comment by djacob65** [comment]
@mjmg I found out that the problem is due to wrong internal parameters related to the AI-binning method. See below the resulting bucketing with some internal parameters more adapted for 13C

![Capture](https://user-images.githubusercontent.com/3490052/144413284-76d435e5-ee1a-434c-88f8-3dea58c940ee.PNG)

I'm going to prepare a new release and I will put online the new release on a server test so that you could test on your spectra set and tell me if it works for you.

Cheers

**Comment by djacob65** [comment]
@mjmg  Here is the new release on a test server: https://app-192-168-101-66.vm.openstack.genouest.org/npflow/
Let me know if it is ok for you before I propagate this release to the production server. 
Cheers

**Comment by mjmg** [comment]
Thanks @djacob65, the test build seems to work with our 13C spectra. Would it be also OK for you to test using 31P or other multinuclear spectra just in case we may need to use the platform on other multinuclear NMR dataset?

Please also address my other issue before releasing the next build.
https://github.com/INRA/NMRProcFlow/issues/5

FYI, I'm more likely to use the docker build. We have some workstations using a customized VM image so I will also have to do a docker pull on those images.

Regards

**Comment by djacob65** [comment]
@mjmg  It's great if it works for you. Regarding 31P (the third and last nucleus type that npflow supports so far), we generally prefer to use a VSB approach due to the small number of peaks. If you have a set of 31P to give me so I can test it, that would be cool. Moreover, you can retrieve (pull) the docker given that it already includes the new release. 
Cheers
